<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/0410_%EC%84%B8%EC%85%98_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
X=torch.rand(size=(7,7))
X, X.shape

(tensor([[0.4006, 0.7717, 0.5157, 0.7941, 0.5372, 0.3355, 0.1422],
         [0.0767, 0.6068, 0.3691, 0.9260, 0.6148, 0.8284, 0.7041],
         [0.4046, 0.7830, 0.1889, 0.7278, 0.2101, 0.4865, 0.5148],
         [0.7929, 0.8623, 0.1913, 0.3489, 0.5100, 0.1725, 0.7214],
         [0.3698, 0.7210, 0.2682, 0.1417, 0.1097, 0.7798, 0.6130],
         [0.2544, 0.6919, 0.7831, 0.1334, 0.7108, 0.6992, 0.6898],
         [0.8698, 0.5150, 0.9374, 0.9061, 0.8132, 0.8669, 0.7134]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

2의 텐서에 대해 '(1, 7)' 모양의 다른 랜덤 텐서를 사용하여 행렬 곱셈을 수행합니다(힌트: 두 번째 텐서를 전치해야 할 수도 있습니다).

In [2]:
# Create another random tensor
Y=torch.rand(size=(1,7))
# Perform matrix multiplication
Z=torch.matmul(X,Y.T)
Z, Z.shape

(tensor([[2.2648],
         [2.5430],
         [2.3679],
         [2.5851],
         [2.1640],
         [2.4358],
         [3.5456]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X=torch.rand(size=(7,7))
Y=torch.rand(size=(1,7))

# Matrix multiply tensors
Z=torch.matmul(X,Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

5. 랜덤 시드에 대해 말하자면, 'torch.manual_seed()'로 설정하는 방법을 봤는데 GPU에 해당하는 것이 있나요? (힌트: 이 경우 'torch.cuda'에 대한 문서를 확인해야 합니다)
  * 만약 있다면, GPU 랜덤 시드를 '1234'로 설정하세요.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

모양이 '(2, 3)'인 두 개의 무작위 텐서를 생성하여 둘 다 GPU로 보냅니다(이를 위해서는 GPU에 대한 액세스가 필요합니다). 텐서를 생성할 때 'torch.manual_seed(1234)'를 설정합니다(이는 GPU 무작위 시드일 필요는 없습니다). 출력은 다음과 같아야 합니다:

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A=torch.rand(size=(2,3)).to(device)
tensor_B=torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

6에서 생성한 텐서에 대해 행렬 곱셈을 수행합니다(다시 말해, 텐서 중 하나의 모양을 조정해야 할 수도 있습니다).

In [6]:
# Perform matmul on tensor_A and tensor_B
tensor_C=torch.matmul(tensor_A,tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max=torch.max(tensor_C)

# Find min
min=torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
arg_max=torch.argmax(tensor_C)

# Find arg min
arg_min=torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

모양이 '(1, 1, 1, 10)'인 무작위 텐서를 만든 다음 '1' 차원을 모두 제거한 새로운 텐서를 만들어 모양이 '(10)'인 텐서를 남깁니다. 시드를 만들 때 시드를 '7'로 설정하고 첫 번째 텐서와 그 모양, 두 번째 텐서와 그 모양을 출력합니다.

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D=torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_E=tensor_D.squeeze()

# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
