<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/ESAA_OB_WEEK1_%ED%95%84%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[내용 정리]**

## 텍스트 분석

NLP(National Language Processing): 머신이 인간의 언어를 이해하고 해석하는 데 중점

**텍스트 분석**(Text Analytics, =TA): 비정형 텍스트에서 의미 있는 정보를 추출하는 데 중점
- **텍스트 분류**(Text Classification): 문서가 특정 분류 또는 **카테고리**에 속하는 것을 예측하는 기법 - 지도학습 적용
- **감성 분석**(Sentimaent Analysis): 텍스트에서 나타나는 **주관적인 요소**를 분석하는 기법 - 지도학습, 비지도학습 적용
- **텍스트 요약**(Summarization): 텍스트 내 **중요한 주제**나 중심 사상을 추출하는 기법
- **텍스트 군집화**(Clustering)와 **유사도 측정**: **비슷한 유형의 문서**에 대해 군집화를 수행하는 기법

### 01 텍스트 분석 이해

#### 텍스트 분석 수행 프로세스

1. **텍스트 사전 준비작업**(텍스트 전처리): 텍스트를 피처로 만들기 전에 **토큰화 작업**(클렌징, 대/소문자 변경, 특수문자 삭제), **텍스트 정규화 작업**(의미 없는 단어 제거 작업, 어근 추출)을 수행하는 것을 통칭.
2. **피처 벡터화/추출**: 사전 준비 작업으로 가공된 텍스트에서 피처를 추출하고 벡터 값을 할당. 대표적인 방법은 **BOW**(Count 기반 벡터화, TF-IDF 기반 벡터화)와 **Word2Vec**가 있음.
3. **ML 모델 수립 및 학습/예측/평가**: 피처 벡터화된 데이터 세트에 ML 모델을 적용해 학습/예측/평가 수행.

#### 파이썬 기반의 NLP, 텍스트 분석 패키지

**NLTK**(Natural Language Toolkit for Python): 파이썬의 가장 대표적인 NLP 패키지. 수행 속도가 낮아 실제 대량의 데이터 기반에서 제대로 활용 X.

**Gensim**: 토픽 모델링 분야의 NLP 패키지.

**SpaCy**: 뛰어난 수행 성능의 NLP 패키지.

### 02 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

**텍스트 정규화**: 텍스트를 머신러닝 알고리즘이나 NLP 애플리케이션에 입력 데이터로 사용하기 위해 클렌징, 정제, 토큰화, 어근화 등의 다양한 **사전 작업**을 수행하는 것.
- 클렌징(Cleansing), 토큰화(Tokenization), 필터링/스톱 워드 제거/철자 수정, Stemming, Lemmatiation

#### 클렌징

불필요한 문자, 기호 등을 제거.

#### 텍스트 토큰화

문장 토큰화: 문서에서 문장을 토큰으로 분리.

단어 토큰화: 문장에서 단어를 토큰으로 분리.

##### 문장 토큰화(sentence tokenization)

문장의 마침표, 개행문자(\n) 등 문장의 마지막을 뜻하는 기호에 따라 분리. 정규 표현식에 따라서도 가능함.

각 문장이 가지는 시맨틱적인 의미가 중요한 요소로 사용될 때 사용.

**sent_tokenize**: 각각의 문장으로 구성된 list 객체를 반환.

##### 단어 토큰화(Word Tokenization)

공백, 콤마, 마침표, 개행문자 등으로 단어를 분리. 정규 표현식을 이용해서도 가능함.

단어의 순서가 중요하지 않은 경우 사용.

**word_tokenize**

#### 스톱 워드 제거

스톱 워드(Stop word): 분석에 큰 의미가 없는 단어.

#### Stemming과 Lemmatization

Stemming: 원형 단어로 변환 시 일반적인 방법 or 더 단순화된 방법을 적용하여 원래 단어에서 **일부 철자가 훼손**된 어근 단어를 추출하는 경향

Lemmatization: 문법적인 요소와 더 의미적인 부분을 감안해 **정확한 철자**로 된 어근 단어를 찾음. 변환에 더 오랜 시간을 필요로 함.

### 03 Bag of Words - BOW

BOW 모델: 문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 **빈도 값을 부여**해 피처 값을 추출하는 모델.

BOW 모델의 단점
1. 문맥 의미 반영 부족: 단어의 순서를 고려하지 않아 문장 내 단어의 문맥적 의미 무시.
2. 희소 행렬 문제(희소성, 희소 행렬)
      - 희소 행렬: 대규모의 칼럼으로 구성된 행렬에서 대부분의 값이 0으로 채워지는 행렬. (<-> 밀집 행렬: 대부분의 값이 의미 있는 값으로 채워지는 행렬.)

#### BOW 피처 벡터화

피처 벡터화: 텍스트를 특정 의미를 가지는 숫자형 값인 벡터 값으로 변환하는 것.
1. **카운트 기반**의 벡터화: 피처 값을 부여할 때 Count를 부여하는 경우

2. **TF-IDF**(Term Frequency - Inverse Document Frequency) 기반의 벡터화: Count를 부여하되, **모든 문서에 전반적으로 자주 나타나는 단어에 페널티** 부여.

#### 사이킷런의 Count 및 TF-IDF 벡터화 구현: CountVectorizer, TfidfVectorizer

CountVectorizer: **카운트** 기반의 벡터화 구현 + **텍스트 전처리** 수행
- fit, transform을 통해 피처 벡터화된 객체 반환.

CountVectorizer 입력 파라미터
- max_df: 너무 높은 빈도수의 단어 피처 제거
- min_df: 너무 낮은 빈도수의 단어 피처 제거
- max_features: 추출하는 피처의 개수 지정
- stop_words: 스톱 워드 지정 후 지정된 단어 제거
- n_gram_range: 단어 순서 보강
- analyzer: 피처 추출 수행 단위 지정
- token_pattern: 토큰화를 수행할 정규 표현식 패턴 지정
- tokenizer

피처 벡터화 과정
1. 사전 데이터 가공
2. 토큰화
3. 텍스트 정규화
4. 피처 벡터화

#### BOW 벡터화를 위한 희소 행렬

##### 희소 행렬 - COO 형식

0이 아닌 데이터만 별도의 데이터 배열에 저장하고, 그 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장하는 방식.

사이파이(Scipy)의 sparse 패키지를 이용.

##### 희소 행렬 - CSR 형식

행 위치 배열 내에 있는 고유한 값의 시작 위치만 다시 별도의 위치 배열로 가지는 변환 방식.

사이파이의 csr_matrix 클래스를 이용. - 0이 아닌 데이터 배열, 열 위치 배열, 행 위치 배열의 고유한 값의 시작 위치 배열을 생성 파라미터로 입력.



# **[코드 필사]**

## 텍스트 분석

NLP(National Language Processing): 머신이 인간의 언어를 이해하고 해석하는 데 중점

**텍스트 분석**(Text Analytics, =TA): 비정형 텍스트에서 의미 있는 정보를 추출하는 데 중점
- **텍스트 분류**(Text Classification): 문서가 특정 분류 또는 **카테고리**에 속하는 것을 예측하는 기법 - 지도학습 적용
- **감성 분석**(Sentimaent Analysis): 텍스트에서 나타나는 **주관적인 요소**를 분석하는 기법 - 지도학습, 비지도학습 적용
- **텍스트 요약**(Summarization): 텍스트 내 **중요한 주제**나 중심 사상을 추출하는 기법
- **텍스트 군집화**(Clustering)와 **유사도 측정**: **비슷한 유형의 문서**에 대해 군집화를 수행하는 기법

### 01 텍스트 분석 이해

#### 텍스트 분석 수행 프로세스

1. **텍스트 사전 준비작업**(텍스트 전처리): 텍스트를 피처로 만들기 전에 **토큰화 작업**(클렌징, 대/소문자 변경, 특수문자 삭제), **텍스트 정규화 작업**(의미 없는 단어 제거 작업, 어근 추출)을 수행하는 것을 통칭.
2. **피처 벡터화/추출**: 사전 준비 작업으로 가공된 텍스트에서 피처를 추출하고 벡터 값을 할당. 대표적인 방법은 **BOW**(Count 기반 벡터화, TF-IDF 기반 벡터화)와 **Word2Vec**가 있음.
3. **ML 모델 수립 및 학습/예측/평가**: 피처 벡터화된 데이터 세트에 ML 모델을 적용해 학습/예측/평가 수행.

#### 파이썬 기반의 NLP, 텍스트 분석 패키지

**NLTK**(Natural Language Toolkit for Python): 파이썬의 가장 대표적인 NLP 패키지. 수행 속도가 낮아 실제 대량의 데이터 기반에서 제대로 활용 X.

**Gensim**: 토픽 모델링 분야의 NLP 패키지.

**SpaCy**: 뛰어난 수행 성능의 NLP 패키지.

### 02 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

**텍스트 정규화**: 텍스트를 머신러닝 알고리즘이나 NLP 애플리케이션에 입력 데이터로 사용하기 위해 클렌징, 정제, 토큰화, 어근화 등의 다양한 **사전 작업**을 수행하는 것.
- 클렌징(Cleansing), 토큰화(Tokenization), 필터링/스톱 워드 제거/철자 수정, Stemming, Lemmatiation

#### 클렌징

불필요한 문자, 기호 등을 제거.

#### 텍스트 토큰화

문장 토큰화: 문서에서 문장을 토큰으로 분리.

단어 토큰화: 문장에서 단어를 토큰으로 분리.

##### 문장 토큰화(sentence tokenization)

문장의 마침표, 개행문자(\n) 등 문장의 마지막을 뜻하는 기호에 따라 분리. 정규 표현식에 따라서도 가능함.

각 문장이 가지는 시맨틱적인 의미가 중요한 요소로 사용될 때 사용.

**sent_tokenize**: 각각의 문장으로 구성된 list 객체를 반환.

In [1]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

text_sample='The Matrix is everywhere its all around us, here even in this room. \
            You can see it out your window or on your television. \
            You feel it when you go to work, or go to church or pay your taxes.'
sentences=sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


##### 단어 토큰화(Word Tokenization)

공백, 콤마, 마침표, 개행문자 등으로 단어를 분리. 정규 표현식을 이용해서도 가능함.

단어의 순서가 중요하지 않은 경우 사용.

**word_tokenize**:

In [2]:
from nltk import word_tokenize

sentence="The Matrix is everywhere its all around us, here even in this room."
words=word_tokenize(sentence)
print(type(words),len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [3]:
from nltk import word_tokenize, sent_tokenize

# 여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):
  # 문장별로 분리 토큰
  sentences=sent_tokenize(text)
  # 분리된 문장별 단어 토큰화
  word_tokens=[word_tokenize(sentence) for sentence in sentences]
  return word_tokens

# 여러 문장에 대해 문장별 단어 토큰화 수행.
word_tokens=tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


**n-gram**: 연속된 n개의 단어를 하나의 토큰화 단위로 분리.

#### 스톱 워드 제거

스톱 워드(Stop word): 분석에 큰 의미가 없는 단어.

In [4]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
print('영어 stop words 개수:',len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [6]:
import nltk

stopwords=nltk.corpus.stopwords.words('english')
all_tokens=[]
# 위 예제에서 3개의 문장별로 얻은 word_tokens list에 대해 스톱 워드를 제거하는 반복문
for sentence in word_tokens:
  filtered_words=[]
  # 개별 문장별로 토큰화된 문장 list에 대해 스톱 워드를 제거하는 반복문
  for word in sentence:
    # 소문자로 모두 변환합니다.
    word=word.lower()
    # 토큰화된 개별 단어가 스톱 워드의 단어에 포함되지 않으면 word_tokens에 추가
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


#### Stemming과 Lemmatization

Stemming: 원형 단어로 변환 시 일반적인 방법 or 더 단순화된 방법을 적용하여 원래 단어에서 **일부 철자가 훼손**된 어근 단어를 추출하는 경향

Lemmatization: 문법적인 요소와 더 의미적인 부분을 감안해 **정확한 철자**로 된 어근 단어를 찾음. 변환에 더 오랜 시간을 필요로 함.

In [7]:
from nltk.stem import LancasterStemmer
stemmer=LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [8]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma=WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

[nltk_data] Downloading package wordnet to /root/nltk_data...


amuse amuse amuse
happy happy
fancy fancy


### 03 Bag of Words - BOW

BOW 모델: 문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 **빈도 값을 부여**해 피처 값을 추출하는 모델.

BOW 모델의 단점
1. 문맥 의미 반영 부족: 단어의 순서를 고려하지 않아 문장 내 단어의 문맥적 의미 무시.
2. 희소 행렬 문제(희소성, 희소 행렬)
      - 희소 행렬: 대규모의 칼럼으로 구성된 행렬에서 대부분의 값이 0으로 채워지는 행렬. (<-> 밀집 행렬: 대부분의 값이 의미 있는 값으로 채워지는 행렬.)

#### BOW 피처 벡터화

피처 벡터화: 텍스트를 특정 의미를 가지는 숫자형 값인 벡터 값으로 변환하는 것.
1. **카운트 기반**의 벡터화: 피처 값을 부여할 때 Count를 부여하는 경우

2. **TF-IDF**(Term Frequency - Inverse Document Frequency) 기반의 벡터화: Count를 부여하되, **모든 문서에 전반적으로 자주 나타나는 단어에 페널티** 부여.

#### 사이킷런의 Count 및 TF-IDF 벡터화 구현: CountVectorizer, TfidfVectorizer

CountVectorizer: **카운트** 기반의 벡터화 구현 + **텍스트 전처리** 수행
- fit, transform을 통해 피처 벡터화된 객체 반환.

CountVectorizer 입력 파라미터
- max_df: 너무 높은 빈도수의 단어 피처 제거
- min_df: 너무 낮은 빈도수의 단어 피처 제거
- max_features: 추출하는 피처의 개수 지정
- stop_words: 스톱 워드 지정 후 지정된 단어 제거
- n_gram_range: 단어 순서 보강
- analyzer: 피처 추출 수행 단위 지정
- token_pattern: 토큰화를 수행할 정규 표현식 패턴 지정
- tokenizer

피처 벡터화 과정
1. 사전 데이터 가공
2. 토큰화
3. 텍스트 정규화
4. 피처 벡터화

#### BOW 벡터화를 위한 희소 행렬

##### 희소 행렬 - COO 형식

0이 아닌 데이터만 별도의 데이터 배열에 저장하고, 그 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장하는 방식.

사이파이(Scipy)의 sparse 패키지를 이용.

In [10]:
import numpy as np

dense=np.array([[3,0,1],[0,2,0]])

In [11]:
from scipy import sparse

# 0이 아닌 데이터 추출
data=np.array([3,1,2])

# 행 위치와 열 위치를 각각 배열로 생성
row_pos=np.array([0,0,1])
col_pos=np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo=sparse.coo_matrix((data,(row_pos,col_pos)))

In [12]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

##### 희소 행렬 - CSR 형식

행 위치 배열 내에 있는 고유한 값의 시작 위치만 다시 별도의 위치 배열로 가지는 변환 방식.

사이파이의 csr_matrix 클래스를 이용. - 0이 아닌 데이터 배열, 열 위치 배열, 행 위치 배열의 고유한 값의 시작 위치 배열을 생성 파라미터로 입력.

In [13]:
from scipy import sparse

dense2=np.array([[0,0,1,0,0,5],
                 [1,4,0,3,2,5],
                 [0,6,0,3,0,0],
                 [2,0,0,0,0,0],
                 [0,0,0,7,0,8],
                 [0,0,0,7,0,8],
                 [1,0,0,0,0,0]])

# 0이 아닌 데이터 추출
data2=np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

# 행 위치와 열 위치를 각각 array로 생성
row_pos=np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos=np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환
sparse_coo=sparse.coo_matrix((data2,(row_pos,col_pos)))

# 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind=np.array([0,2,7,9,10,12,13])

# CSR 형식으로 변환
sparse_csr=sparse.csr_matrix((data2,col_pos,row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [14]:
dense3=np.array([[0,0,1,0,0,5],
                 [1,4,0,3,2,5],
                 [0,6,0,3,0,0],
                 [2,0,0,0,0,0],
                 [0,0,0,7,0,8],
                 [0,0,0,7,0,8],
                 [1,0,0,0,0,0]])

coo=sparse.coo_matrix(dense3)
csr=sparse.csr_matrix(dense3)