<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector=np.zeros(10,dtype='int32')
print(null_vector)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array0=null_vector
print('memory size is:', array0.nbytes)

memory size is: 40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector1=np.zeros(10,dtype='int32')
null_vector1[4]=1
print(null_vector1)

[0 0 0 0 1 0 0 0 0 0]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector1=np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector2=np.sort(vector1)[::-1]
print(vector2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1=np.arange(0,9)
array2=array1.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array3=np.array([1,2,0,0,4,0])
array4=array3[array3!=0]
print('indices are:', array4)

indices are: [1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random_matrix=np.random.random((3,3,3))
print(random_matrix)

[[[0.85942471 0.41369672 0.31267118]
  [0.71716211 0.47265166 0.56473525]
  [0.94574658 0.38932182 0.27641345]]

 [[0.03940315 0.05575202 0.27906652]
  [0.24391157 0.72324182 0.84130238]
  [0.84899442 0.42288616 0.16212319]]

 [[0.77944031 0.5641967  0.93486728]
  [0.01886856 0.83795474 0.94448325]
  [0.54697479 0.45644809 0.05854923]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_matrix1=np.random.random((10,10))
print(random_matrix1)
print('minimum is:', np.min(random_matrix1))
print('maximum is:', np.max(random_matrix1))

[[0.75614048 0.09227457 0.09647113 0.74447258 0.60925578 0.35260216
  0.47752519 0.02473188 0.91181407 0.02866195]
 [0.30024338 0.88661764 0.98385014 0.03978733 0.69397013 0.24135818
  0.1732182  0.5565452  0.83524209 0.38732791]
 [0.55053457 0.22334528 0.63341001 0.0942216  0.66549778 0.97265672
  0.93031976 0.86195985 0.03053527 0.13964711]
 [0.77293701 0.39394198 0.23868902 0.41470815 0.48259562 0.03264444
  0.28067042 0.90123391 0.31695348 0.45386934]
 [0.54008338 0.02762761 0.01714281 0.57185472 0.00760337 0.96922788
  0.11989161 0.40589307 0.6312829  0.47943285]
 [0.68601297 0.54896592 0.11915799 0.42281541 0.71564156 0.26571416
  0.75340574 0.35222086 0.69466755 0.96964118]
 [0.00704859 0.12421902 0.08447711 0.04135905 0.26825233 0.26548822
  0.16201051 0.7202545  0.86663836 0.24641234]
 [0.41603393 0.23739805 0.61587282 0.59609831 0.87311823 0.34476276
  0.97833997 0.76269322 0.15470854 0.64439703]
 [0.78409741 0.63760715 0.07379062 0.69335293 0.85423971 0.63377885
  0.76808983

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
vector30=np.random.random(30)
print(vector30)
print('mean is:', np.mean(vector30))

[0.1855335  0.56823018 0.33275876 0.0391106  0.82252158 0.31935421
 0.80210979 0.18478272 0.2745577  0.53075548 0.89900179 0.18685947
 0.3820729  0.14147924 0.50521503 0.07897711 0.74569017 0.67998463
 0.85654015 0.05198539 0.5340759  0.56610851 0.09243643 0.43372669
 0.19078436 0.50704273 0.29383452 0.27208252 0.2492259  0.99449715]
mean is: 0.4240445046060402


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [10]:
array2d=np.zeros(25,dtype='int32')
array2d_1=array2d.reshape(5,5)
array2d_1[0]=1
array2d_1[4]=1
array2d_1[:,0]=1
array2d_1[:,4]=1
print(array2d_1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [17]:
matrix=np.zeros((5,5),dtype='int32')
matrix[1,0]=1
matrix[2,1]=2
matrix[3,2]=3
matrix[4,3]=4
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [25]:
matrix88=np.zeros(64,dtype='int32')
matrix88_1=matrix88.reshape(8,8)
matrix88_1[1::2,::2]=1
matrix88_1[::2,1::2]=1
print(matrix88_1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [38]:
index100=np.unravel_index(100,(6,7,8))
print(index100)

(np.int64(1), np.int64(5), np.int64(4))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [46]:
random_matrix2=np.random.random((5,5))
xbar=np.mean(random_matrix2)
S=np.std(random_matrix2)
Z=(random_matrix2-xbar)/S
print(Z)

[[-2.05840867  1.26816923  0.44314816  0.65807672  1.39362936]
 [ 0.03210886  1.10621869 -0.80460376  0.59709072  0.61624704]
 [ 0.97430515 -1.37690447 -1.63739197  0.58890874 -0.93011164]
 [-1.97583175 -0.17898384  1.01381793  0.49804914 -0.96505256]
 [ 0.24373205  0.60137792  0.62969066 -0.32385817 -0.41342352]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [54]:
color_dtype=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
