<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/ESAA_OB_WEEK3_%ED%95%84%EC%82%AC2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[내용 정리]**

## 01 추천 시스템의 개요와 배경

### 추천 시스템의 개요

### 온라인 스토어의 필수 요소, 추천 시스템

추천 시스템으로 사용자의 선택 부담을 해결 (너무 많은 상품, 한정된 시간 동안 선택의 압박)

###  추천 시스템의 유형

콘텐츠 기반 필터링(Content based filtering) 방식

협업 필터링(Collaborative Filtering) 방식
- 최근접 이웃(Nearest Neighbor) 협업 필터링
- 잠재 요인(Latent Factor) 협업 필터링

## 02 콘텐츠 기반 필터링 추천 시스템

사용자가 특정한 아이템을 매우 선호하는 경우 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식

## 03 최근접 이웃 협업 필터링

협업 필터링(Collaborative Filtering) 방식: 사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 **사용자 행동 양식**(User Behavior)만을 기반으로 추천을 수행하는 것.
- 사용자-아이템 평점 매트릭스와 같은 **축적된 사용자 행동 데이터를 기반**으로 사용자가 아직 평가하지 않은 아이템을 **예측 평가**(Predicted Rating)하는 것.
   - 최근접 이웃 방식과 잠재 요인 방식 모두 **사용자-아이템 평점 행렬 데이터**에 의지.

**사용자-아이템 평점 행렬 데이터**
- 행: 개별 사용자, 열: 개별 아이템
- 희소 행렬(Sparse Matrix) 특성을 가짐.

최근접 이웃 협업 필터링(=메모리 협업 필터링)
- 사용자 기반(User-User): 당신과 비슷한 고객들이 다음 상품도 구매했습니다. - **특정 사용자와 타 사용자 간의 유사도**를 측정. 유사도가 높은 Top-N 사용자를 추출해 그들의 선호 아이템을 추천.
- 아이템 기반(Item-Item): 이 상품을 선택한 다른 고객들은 다음 상품도 구매했습니다. - **아이템이 가지는 속성과 상관없이** 사용자들이 그 아이템을 좋아하는지/싫어하는지의 평가 척도가 유사한 아이템을 추천하는 기준이 되는 알고리즘

## 04 잠재 요인 협업 필터링

### 잠재 요인 협업 필터링의 이해

사용자-아이템 평점 매트릭스 속에 숨어 있는 **잠재 요인**을 추출해 추천 예측을 할 수 있게 하는 기법.

행렬 분해(Matrix Factorization): 대규모 다차원 행렬을 SVD와 같은 차원 감소 기법으로 분해하는 과정에서 잠재 요인 추출

**잠재 요인**을 기반으로 다차원 희소 행렬인 사용자-아이템 행렬 데이터를 저차원 밀집 행렬의 사용자-잠재 요인 행렬/아이템-잠재 요인 행렬의 전치 행렬(=**잠재 요인-아이템 행렬**)로 분해. 새로운 예측 사용자-아이템 평점 행렬 데이터를 만들어 **평점을 부여하지 않은 아이템에 예측 평점을 생성**하는 것.

### 행렬 분해의 이해

행렬 분해: 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법.
- EX) SVD(Singular Vector Decomposition), NMF(Non-Negative Matrix Factorization) 등


- M: 총 사용자 수
- N: 총 아이템 수
- K: 잠재 요인의 차원 수
- R: M X N 차원의 사용자-아이템 평점 행렬
- P: M X K 차원의 사용자-잠재 요인 행렬
- Q: N X K 차원의 아이템-잠재 요인 행렬
- Q.T: Q의 전치 행렬, 잠재 요인-아이템 행렬

SVD: 널 값이 없는 행렬에만 적용 가능. <-> 널 값이 있는 행렬에는 확률적 경사 하강법, ALS(Alternating Least Squares) 이용.

### 확률적 경사 하강법을 이용한 행렬 분해

확률적 경사 하강법(Stochastic Gradient Descent: SGD)을 이용한 행렬 분해
1. P와 Q를 임의의 값을 가진 행렬로 설정.
2. P와 Q.T 값을 곱해 예측 R 행렬을 계산, 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값을 계산.
3. **이 오류 값을 최소화할 수 있도록 P와 Q 행렬을 적절한 값으로 각각 업데이트.**
4. 2, 3번 작업을 반복하며 P와 Q 값을 업데이트해 근사화.

사용자-아이템 평점 행렬의 경우 단순히 예측 오류값의 최소화와 학습 시 과적합을 피하기 위해 규제를 반영한 비용 함수를 적용. - **L2 규제** 반영.

# **[코드 필사]**

## 01 추천 시스템의 개요와 배경

### 추천 시스템의 개요

### 온라인 스토어의 필수 요소, 추천 시스템

추천 시스템으로 사용자의 선택 부담을 해결 (너무 많은 상품, 한정된 시간 동안 선택의 압박)



###  추천 시스템의 유형

콘텐츠 기반 필터링(Content based filtering) 방식

협업 필터링(Collaborative Filtering) 방식
- 최근접 이웃(Nearest Neighbor) 협업 필터링
- 잠재 요인(Latent Factor) 협업 필터링

## 02 콘텐츠 기반 필터링 추천 시스템

사용자가 특정한 아이템을 매우 선호하는 경우 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식

## 03 최근접 이웃 협업 필터링

협업 필터링(Collaborative Filtering) 방식: 사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 **사용자 행동 양식**(User Behavior)만을 기반으로 추천을 수행하는 것.
- 사용자-아이템 평점 매트릭스와 같은 **축적된 사용자 행동 데이터를 기반**으로 사용자가 아직 평가하지 않은 아이템을 **예측 평가**(Predicted Rating)하는 것.
   - 최근접 이웃 방식과 잠재 요인 방식 모두 **사용자-아이템 평점 행렬 데이터**에 의지.

**사용자-아이템 평점 행렬 데이터**
- 행: 개별 사용자, 열: 개별 아이템
- 희소 행렬(Sparse Matrix) 특성을 가짐.

최근접 이웃 협업 필터링(=메모리 협업 필터링)
- 사용자 기반(User-User): 당신과 비슷한 고객들이 다음 상품도 구매했습니다. - **특정 사용자와 타 사용자 간의 유사도**를 측정. 유사도가 높은 Top-N 사용자를 추출해 그들의 선호 아이템을 추천.
- 아이템 기반(Item-Item): 이 상품을 선택한 다른 고객들은 다음 상품도 구매했습니다. - **아이템이 가지는 속성과 상관없이** 사용자들이 그 아이템을 좋아하는지/싫어하는지의 평가 척도가 유사한 아이템을 추천하는 기준이 되는 알고리즘

## 04 잠재 요인 협업 필터링

### 잠재 요인 협업 필터링의 이해

사용자-아이템 평점 매트릭스 속에 숨어 있는 **잠재 요인**을 추출해 추천 예측을 할 수 있게 하는 기법.

행렬 분해(Matrix Factorization): 대규모 다차원 행렬을 SVD와 같은 차원 감소 기법으로 분해하는 과정에서 잠재 요인 추출

**잠재 요인**을 기반으로 다차원 희소 행렬인 사용자-아이템 행렬 데이터를 저차원 밀집 행렬의 사용자-잠재 요인 행렬/아이템-잠재 요인 행렬의 전치 행렬(=**잠재 요인-아이템 행렬**)로 분해. 새로운 예측 사용자-아이템 평점 행렬 데이터를 만들어 **평점을 부여하지 않은 아이템에 예측 평점을 생성**하는 것.

### 행렬 분해의 이해

행렬 분해: 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법.
- EX) SVD(Singular Vector Decomposition), NMF(Non-Negative Matrix Factorization) 등


- M: 총 사용자 수
- N: 총 아이템 수
- K: 잠재 요인의 차원 수
- R: M X N 차원의 사용자-아이템 평점 행렬
- P: M X K 차원의 사용자-잠재 요인 행렬
- Q: N X K 차원의 아이템-잠재 요인 행렬
- Q.T: Q의 전치 행렬, 잠재 요인-아이템 행렬

SVD: 널 값이 없는 행렬에만 적용 가능. <-> 널 값이 있는 행렬에는 확률적 경사 하강법, ALS(Alternating Least Squares) 이용.


### 확률적 경사 하강법을 이용한 행렬 분해

확률적 경사 하강법(Stochastic Gradient Descent: SGD)을 이용한 행렬 분해
1. P와 Q를 임의의 값을 가진 행렬로 설정.
2. P와 Q.T 값을 곱해 예측 R 행렬을 계산, 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값을 계산.
3. **이 오류 값을 최소화할 수 있도록 P와 Q 행렬을 적절한 값으로 각각 업데이트.**
4. 2, 3번 작업을 반복하며 P와 Q 값을 업데이트해 근사화.

사용자-아이템 평점 행렬의 경우 단순히 예측 오류값의 최소화와 학습 시 과적합을 피하기 위해 규제를 반영한 비용 함수를 적용. - **L2 규제** 반영.

In [1]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정
R=np.array([[4,np.nan,np.nan,2,np.nan],
            [np.nan,5,np.nan,3,1],
            [np.nan,np.nan,3,4,4],
            [5,2,1,2,np.nan]])
num_users,num_items=R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다
np.random.seed(1)
P=np.random.normal(scale=1./K,size=(num_users,K))
Q=np.random.normal(scale=1./K,size=(num_items,K))

In [2]:
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
  error=0
  # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
  full_pred_matrix=np.dot(P,Q.T)

  # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
  x_non_zero_ind=[non_zero[0] for non_zero in non_zeros]
  y_non_zero_ind=[non_zero[1] for non_zero in non_zeros]
  R_non_zeros=R[x_non_zero_ind,y_non_zero_ind]
  full_pred_matrix_non_zeros=full_pred_matrix[x_non_zero_ind,y_non_zero_ind]
  mse=mean_squared_error(R_non_zeros,full_pred_matrix_non_zeros)
  rmse=np.sqrt(mse)

  return rmse

In [4]:
# R>0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장
non_zeros=[(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]

steps=1000
learning_rate=0.01
r_lambda=0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트
for step in range(steps):
  for i, j, r in non_zeros:
    # 실제 값과 예측 값의 차이인 오류 값 구함
    eij=r-np.dot(P[i,:],Q[j,:].T)
    # Regularization을 반영한 SGD 업데이트 공식 적용
    P[i,:]=P[i,:]+learning_rate*(eij*Q[j,:]-r_lambda*P[i,:])
    Q[j,:]=Q[j,:]+learning_rate*(eij*P[i,:]-r_lambda*Q[j,:])

  rmse=get_rmse(R,P,Q,non_zeros)
  if (step%50)==0:
    print("### iteration step: ",step,"rmse:",rmse)

### iteration step:  0 rmse: 3.0148041897560884
### iteration step:  50 rmse: 0.3840649007304081
### iteration step:  100 rmse: 0.24599129098006053
### iteration step:  150 rmse: 0.2049507662286798
### iteration step:  200 rmse: 0.18116669644528233
### iteration step:  250 rmse: 0.16325046610539945
### iteration step:  300 rmse: 0.14786620927950342
### iteration step:  350 rmse: 0.13385098067035633
### iteration step:  400 rmse: 0.12073637677866515
### iteration step:  450 rmse: 0.10829681319681746
### iteration step:  500 rmse: 0.09640734195640609
### iteration step:  550 rmse: 0.08501863963256243
### iteration step:  600 rmse: 0.07417091000014626
### iteration step:  650 rmse: 0.06399890005057708
### iteration step:  700 rmse: 0.054704029712349625
### iteration step:  750 rmse: 0.04649722604491869
### iteration step:  800 rmse: 0.0395359483186462
### iteration step:  850 rmse: 0.03388051961188911
### iteration step:  900 rmse: 0.02948189872198489
### iteration step:  950 rmse: 0.0261

In [5]:
pred_matrix=np.dot(P,Q.T)
print('예측 행렬:\n',np.round(pred_matrix,3))

예측 행렬:
 [[4.003 1.782 1.065 1.976 1.544]
 [5.209 4.978 0.112 2.983 1.004]
 [9.333 2.367 2.977 3.977 3.987]
 [4.956 2.002 1.03  2.037 1.682]]
