<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/ESAA_OB_WEEK5_%ED%95%84%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[내용 정리]**

## 1.1 인공지능, 머신 러닝과 딥러닝

인공지능 > 머신러닝(인공 신경망, 서포트 벡터 머신, 결정 트리) > 딥러닝(CNN, RNN, RBM)

머신러닝: 각 데이터 특성을 컴퓨터에 인식시키고 학습 시켜 문제를 해결. **주어진 데이터를 인간이 먼저 처리**
- 동일한 유형의 데이터 분석을 위한 재사용 불가능
- 수천 개의 데이터 필요
- 단시간의 훈련 시간
- 점수 또는 분류 등 숫자 값으로 결과 도출

딥러닝: 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석.
- 구현된 알고리즘은 동일한 유형의 데이터를 분석하는 데 재사용
- 수백만 개 이상의 데이터 필요
- 장시간의 훈련 시간
- 점수, 텍스트, 소리 등 어떤 것이든 가능함.

## 1.2 머신 러닝이란

### 1.2.1 머신 러닝 학습 과정

학습 단계: 훈련 데이터를 머신 러닝 알고리즘에 적용해 학습시키고 학습 결과로 모형이 생성됨.

예측 단계: 생성된 모형에 새로운 데이터를 적용하여 결과 예측.

특성 추출: 컴퓨터가 입력받은 데이터를 분석하여 일정한 패턴이나 규칙을 찾아내게 하기 위해 사람이 인지하는 데이터를 컴퓨터가 인지할 수 있는 데이터로 변환해 주는 작업.

훈련과 검증, 테스트 데이터셋
- 모델 성능을 평가하기 위해, 훈련 데이터셋으로 학습시킨 모델이 잘 예측하는지 성능을 평가하기 위해 검증 데이터셋 사용.

### 1.2.2 머신 러닝 학습 알고리즘

지도학습: 정답이 무엇인지 컴퓨터에게 알려 주고 학습시키는 방법
- 분류: K-최근접 이웃, 서포트 벡터 머신, 결정 트리, 로지스틱 회귀
- 회귀: 선형 회귀

비지도학습: 정답을 알려 주지 않고 특징이 비슷한 데이터를 클러스터링하여 예측하는 학습 방법.
- 군집: K-평균 군집화, 밀도 기반 군집 분석
- 차원 축소: 주성분 분석

강화학습 - 마르코프 결정 과정

## 1.3 딥러닝이란

### 1.3.1 딥러닝 학습 과정

데이터 준비
1. 파이토치, 케라스에서 제공하는 데이터셋 사용(전처리가 끝난 데이터)
2. 캐글 등 공개된 데이터 사용

모델 정의: 신경망 생성. 은닉층 개수 조절 필요.(많을수록 성능이 좋아지지만 과적합 발생 가능.)

모델 컴파일: 활성화 함수, 손실 함수, 옵티마이저 선택

모델 훈련: 한 번에 처리할 데이터양 지정. 배치(전체 훈련 데이터셋에서 일정한 묶음으로 나누어 처리)와 에포크(훈련의 횟수) 선택.

모델 예측: 검증 데이터셋을 생성한 모델에 적용해 실제 예측을 진행.

**신경망**(입력층-은닉층-출력층), **역전파**(가중치 값 없데이트)

### 1.3.2 딥러닝 학습 알고리즘

**지도학습**
- 합성곱 신경망(Convolutional Neural Network, CNN)
   - 이미지 분류
   - 이미지 인식
   - 이미지 분할: 영상에서 사물이나 배경 등 객체 간 영역을 픽셀 단위로 구분하는 기술. X-ray, CT, MRI
- 순환 신경망(Recurrent Neural Network, RNN): 시계열 데이터를 분류할 때 사용.
   - LSTM(Long Short-Term Memory): 게이트(망각, 입력, 출력)를 세 개 추가해 역전파 과정에서의 기울기 소멸 문제를 해결한 것.

**비지도학습**
- 워드 임베딩(Word Embedding): 자연어 변환 과정에서 단어를 벡터로 표현. 워드투벡터(Word2Vec), 글로브(GloVe)
- 군집: 한 클러스터 안의 데이터는 매우 비슷하게 구성하고 다른 클러스터의 데이터와 구분되도록 나누는 것.

**전이학습**(transfer learning): 사전에 학습이 완료된 모델을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법.
- 사전 학습 모델: 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모델. VGG, 인셉션, MobileNet 등.

**강화학습**

## 2.1 파이토치 개요

넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우

최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

**간결하고 빠른 구현성**

### 2.1.1. 파이토치 특징 및 장점

**GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크**

**GPU**: 연산 속도를 빠르게 하는 역할
- 기울기 계산을 위해 미분을 사용할 때 빠른 계산 가능.

**텐서**: 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬. '변수.cuda()'로 GPU 연산 수행.

**동적 신경망**: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망. 'Define by Run' 방식 사용.

- 효율적인 계산(파이썬 환경과 쉽게 통합, 디버깅이 직관적이고 간결함.)
- 낮은 CPU 활용으로 학습 및 추론 속도가 빠르고 다루기 쉬움.
- 잦은 API 변경이 없음.

### 2.1.2 파이토치의 아키텍처

**파이토치 API**: 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 함. C++로 작성된 파이토치 엔진으로 계산 작업을 전달하는 역할.
- torch: GPU 지원 텐서 패키지
- torch.autograd: 자동 미분 패키지
- torch.nn: 신경망 구축 및 훈련 패키지
- torch.multiprocessing: 파이썬 멀티프로세싱 패키지
- torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지

**파이토치 엔진**: Autograd C++(미분 자동 계산), Aten C++(C++ 텐서 라이브러리 제공), JIT C++(JIT 컴파일러), Python API로 구성.

**연산 처리**: CPU, GPU를 이용하여  효율적인 데이터 구조, 다차원 텐서에 대한 연산 처리.

**텐서를 메모리에 저장하기**
- 오프셋(offset): 텐서에서 첫 번째 요소가 스토리지에 저장된 인덱스
- 스트라이드(stride): 각 차원에 따라 다음 요소를 얻기 위해 건너뛰기가 필요한 스토리지 요소 개수.

## 2.2 파이토치 기초 문법

### 2.2.1 텐서 다루기

#### 텐서 생성 및 변환

#### 텐서의 인덱스 조작

torch.FloatTensor: 32비트의 부동 소수점

torch.DoubleTensor: 64비트의 부동 소수점

torch.LongTensor: 64비트의 부호가 있는 정수

#### 텐서 연산 및 차원 조작

텐서 간의 타입이 다르면 연산 불가능

view: 텐서의 차원 변경. 이 외에도 stack, t, transpose 사용.

### 2.2.2 데이터 준비

#### 단순하게 파일을 불러와서 사용

JSON, PDF, CSV 등의 파일을 불러오는 방법

#### 커스텀 데이터셋을 만들어서 사용

데이터로더 객체: 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할 때 배치 크기만큼 데이터를 꺼내서 사용. 반복자에 포함된 인덱스를 이용해 배치 크기만큼 데이터를 반환.

#### 파이토치에서 제공하는 데이터셋 사용

토치비전(torchvision)

https://pytorch.org/vision/O.8/datasets.html

### 2.2.3 모델 정의

계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층으로 합성곱층(convolutional layer), 선형계층(linear layer)

모듈(module): 한 개 이상의 계층이 모여서 구성된 것.

모델(model): 최종적으로 원하는 네트워크

#### 단순 신경망을 정의하는 방법

#### nn.Moduel()을 상속하여 정의하는 방법

#### Sequential 신경망을 정의하는 방법

nn.Sequential: 네트워크 모델 정의, 계층이 복잡할수록 효과가 뛰어남.

model.modules(): 모델의 네트워크에 대한 모든 노드 반환

model.children(): 같은 수주의 하위 노드 반환

#### 함수로 신경망을 정의하는 방법

nn.Model() 상속받아 사용.

### 2.2.4 모델의 파라미터 정의

**손실 함수**(loss function): 학습하는 동안 출력과 실제 값 사이의 오차 측정
- BCELoss: 이진 분류
- CrossEntropyLoss: 다중 클래스 분류
- MSELoss: 회귀 모델

**옵티마이저**(optimizer): 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법 결정.

**학습률 스케줄러**(learning rate scheduler): 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시킴.
- optim.lr_scheduler.LambdaLR
- optim.lr_scheduler.StepLR
- optim.lr_scheduler.MultiStepLR
- optim.lr_scheduler.ExponentialLR
- optim.lr_scheduler.CosineAnnealingLR
- optim.lr_scheduler.CosineAnnealingLR

**지표**: 훈련과 테스트 단계 모니터링

### 2.2.5 모델 훈련

모델, 손실 함수, 옵티마이저 정의

-> optimizer.zero_grad(): 전방향 학습, 기울기 초기화

-> output=model(input): 출력 계산

-> loss=loss_fn(output,target): 오차 계산

-> loss.backword(): 역전파 학습

-> optimizer.step(): 기울기 업데이트

### 2.2.6 모델 평가

### 2.2.7 훈련 과정 모니터링

1. 텐서보드를 설정(set up)
2. 텐서보드에 기록(write)
3. 텐서보드를 사용하여 모델 구조를 살펴봄.

model.train: 훈련 데이터셋에 사용하며 모델 훈련이 진행될 것을 알림. 드롭아웃 활성화.

model.eval: 모델 평가할 때 모든 노드를 사용하겠다는 의미로 검증과 테스트 데이터셋에 사용.

# **[코드 필사]**

## 1.1 인공지능, 머신 러닝과 딥러닝

인공지능 > 머신러닝(인공 신경망, 서포트 벡터 머신, 결정 트리) > 딥러닝(CNN, RNN, RBM)

머신러닝: 각 데이터 특성을 컴퓨터에 인식시키고 학습 시켜 문제를 해결. **주어진 데이터를 인간이 먼저 처리**
- 동일한 유형의 데이터 분석을 위한 재사용 불가능
- 수천 개의 데이터 필요
- 단시간의 훈련 시간
- 점수 또는 분류 등 숫자 값으로 결과 도출

딥러닝: 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석.
- 구현된 알고리즘은 동일한 유형의 데이터를 분석하는 데 재사용
- 수백만 개 이상의 데이터 필요
- 장시간의 훈련 시간
- 점수, 텍스트, 소리 등 어떤 것이든 가능함.

## 1.2 머신 러닝이란

### 1.2.1 머신 러닝 학습 과정

학습 단계: 훈련 데이터를 머신 러닝 알고리즘에 적용해 학습시키고 학습 결과로 모형이 생성됨.

예측 단계: 생성된 모형에 새로운 데이터를 적용하여 결과 예측.

특성 추출: 컴퓨터가 입력받은 데이터를 분석하여 일정한 패턴이나 규칙을 찾아내게 하기 위해 사람이 인지하는 데이터를 컴퓨터가 인지할 수 있는 데이터로 변환해 주는 작업.

훈련과 검증, 테스트 데이터셋
- 모델 성능을 평가하기 위해, 훈련 데이터셋으로 학습시킨 모델이 잘 예측하는지 성능을 평가하기 위해 검증 데이터셋 사용.

### 1.2.2 머신 러닝 학습 알고리즘

지도학습: 정답이 무엇인지 컴퓨터에게 알려 주고 학습시키는 방법
- 분류: K-최근접 이웃, 서포트 벡터 머신, 결정 트리, 로지스틱 회귀
- 회귀: 선형 회귀

비지도학습: 정답을 알려 주지 않고 특징이 비슷한 데이터를 클러스터링하여 예측하는 학습 방법.
- 군집: K-평균 군집화, 밀도 기반 군집 분석
- 차원 축소: 주성분 분석

강화학습 - 마르코프 결정 과정

## 1.3 딥러닝이란

### 1.3.1 딥러닝 학습 과정

데이터 준비
1. 파이토치, 케라스에서 제공하는 데이터셋 사용(전처리가 끝난 데이터)
2. 캐글 등 공개된 데이터 사용

모델 정의: 신경망 생성. 은닉층 개수 조절 필요.(많을수록 성능이 좋아지지만 과적합 발생 가능.)

모델 컴파일: 활성화 함수, 손실 함수, 옵티마이저 선택

모델 훈련: 한 번에 처리할 데이터양 지정. 배치(전체 훈련 데이터셋에서 일정한 묶음으로 나누어 처리)와 에포크(훈련의 횟수) 선택.

모델 예측: 검증 데이터셋을 생성한 모델에 적용해 실제 예측을 진행.

**신경망**(입력층-은닉층-출력층), **역전파**(가중치 값 없데이트)

### 1.3.2 딥러닝 학습 알고리즘

**지도학습**
- 합성곱 신경망(Convolutional Neural Network, CNN)
   - 이미지 분류
   - 이미지 인식
   - 이미지 분할: 영상에서 사물이나 배경 등 객체 간 영역을 픽셀 단위로 구분하는 기술. X-ray, CT, MRI
- 순환 신경망(Recurrent Neural Network, RNN): 시계열 데이터를 분류할 때 사용.
   - LSTM(Long Short-Term Memory): 게이트(망각, 입력, 출력)를 세 개 추가해 역전파 과정에서의 기울기 소멸 문제를 해결한 것.

**비지도학습**
- 워드 임베딩(Word Embedding): 자연어 변환 과정에서 단어를 벡터로 표현. 워드투벡터(Word2Vec), 글로브(GloVe)
- 군집: 한 클러스터 안의 데이터는 매우 비슷하게 구성하고 다른 클러스터의 데이터와 구분되도록 나누는 것.

**전이학습**(transfer learning): 사전에 학습이 완료된 모델을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법.
- 사전 학습 모델: 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모델. VGG, 인셉션, MobileNet 등.

**강화학습**



## 2.1 파이토치 개요

넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우

최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

**간결하고 빠른 구현성**

### 2.1.1. 파이토치 특징 및 장점

**GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크**

**GPU**: 연산 속도를 빠르게 하는 역할
- 기울기 계산을 위해 미분을 사용할 때 빠른 계산 가능.

**텐서**: 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬. '변수.cuda()'로 GPU 연산 수행.

**동적 신경망**: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망. 'Define by Run' 방식 사용.

- 효율적인 계산(파이썬 환경과 쉽게 통합, 디버깅이 직관적이고 간결함.)
- 낮은 CPU 활용으로 학습 및 추론 속도가 빠르고 다루기 쉬움.
- 잦은 API 변경이 없음.

### 2.1.2 파이토치의 아키텍처

**파이토치 API**: 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 함. C++로 작성된 파이토치 엔진으로 계산 작업을 전달하는 역할.
- torch: GPU 지원 텐서 패키지
- torch.autograd: 자동 미분 패키지
- torch.nn: 신경망 구축 및 훈련 패키지
- torch.multiprocessing: 파이썬 멀티프로세싱 패키지
- torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지

**파이토치 엔진**: Autograd C++(미분 자동 계산), Aten C++(C++ 텐서 라이브러리 제공), JIT C++(JIT 컴파일러), Python API로 구성.

**연산 처리**: CPU, GPU를 이용하여  효율적인 데이터 구조, 다차원 텐서에 대한 연산 처리.

**텐서를 메모리에 저장하기**
- 오프셋(offset): 텐서에서 첫 번째 요소가 스토리지에 저장된 인덱스
- 스트라이드(stride): 각 차원에 따라 다음 요소를 얻기 위해 건너뛰기가 필요한 스토리지 요소 개수.



## 2.2 파이토치 기초 문법

### 2.2.1 텐서 다루기

#### 텐서 생성 및 변환

In [6]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]],device="cuda:0")) # GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]],dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [7]:
temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy()) # GPU 상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

[[1 2]
 [3 4]]


#### 텐서의 인덱스 조작

torch.FloatTensor: 32비트의 부동 소수점

torch.DoubleTensor: 64비트의 부동 소수점

torch.LongTensor: 64비트의 부호가 있는 정수

In [8]:
temp=torch.FloatTensor([1,2,3,4,5,6,7]) # 파이토치로 1차원 벡터 생성
print(temp[0],temp[1],temp[-1]) # 인덱스로 접근
print('----------------')
print(temp[2:5],temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
----------------
tensor([3., 4., 5.]) tensor([5., 6.])


#### 텐서 연산 및 차원 조작

텐서 간의 타입이 다르면 연산 불가능

view: 텐서의 차원 변경. 이 외에도 stack, t, transpose 사용.

In [9]:
v=torch.tensor([1,2,3]) # 길이가 3인 벡터 생성
w=torch.tensor([3,4,6])
print(w-v) # 길이가 같은 벡터 간 뺄셈 연산

tensor([2, 2, 3])


In [10]:
temp=torch.tensor([
    [1,2,],[3,4] # 2*2 행렬 생성
])

print(temp.shape)
print('----------------')
print(temp.view(4,1)) # 2*2 행렬을 4*1로 변형
print('----------------')
print(temp.view(-1)) # 2*2 행렬을 1차원 벡터로 변형
print('----------------')
print(temp.view(1,-1))
print('----------------')
print(temp.view(-1,1))

torch.Size([2, 2])
----------------
tensor([[1],
        [2],
        [3],
        [4]])
----------------
tensor([1, 2, 3, 4])
----------------
tensor([[1, 2, 3, 4]])
----------------
tensor([[1],
        [2],
        [3],
        [4]])


### 2.2.2 데이터 준비

#### 단순하게 파일을 불러와서 사용

JSON, PDF, CSV 등의 파일을 불러오는 방법

In [ ]:
# pip install pandas

In [ ]:
# import pandas as pd
# import torch
# data=pd.read_csv('../class2.csv')

# x=torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
# y=torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

#### 커스텀 데이터셋을 만들어서 사용

데이터로더 객체: 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할 때 배치 크기만큼 데이터를 꺼내서 사용. 반복자에 포함된 인덱스를 이용해 배치 크기만큼 데이터를 반환.

In [ ]:
# class CustomDataset(torch.utils.data.Dataset):
#   def __init__(self):
#   def __len__(self):
#   def __getitem__(self,index):

In [ ]:
# import pandas as pd
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader

# class CustomDataset(Dataset):
#   def __init__(self,csv_file):
#       self.label=pd.read_csv(csv_file)

#   def __len__(self):
#       return len(self.label)

#   def __getitem__(self,idx):
#       sample=torch.tensor(self.label.iloc[idx,0:3]).int()
#       label=torch .tensor(self.label.iloc[idx,3]).int()
#       return sample,label

# tensor_dataset=CustomDataset('../covtype.csv')
# dataset=DataLoader(tensor_dataset,batch_size=4,shuffle=True)

#### 파이토치에서 제공하는 데이터셋 사용

토치비전(torchvision)

https://pytorch.org/vision/O.8/datasets.html

In [ ]:
# !pip install requests

In [ ]:
# import torchvision.transforms as tranforms

# mnist_transform=transforms.Compose([
#    transforms.ToTensor(),
#    transfroms.Normalize((0.5,),(1.0,))])

# from torchvision.datasets import MNIST
# import requests
# download_root='../chap02/data/MNIST_DATASET'

# train_dataset=MNIST(download_root,transfrom=mnist_transform,train=True,
#                     down_load=True)
# valid_dataset=MNIST(download_root,transfrom=mnist_transform,train=False,
#                     down_load=True)
# test_dataset=MNIST(download_root,transfrom=mnist_transform,train=False,
#                    down_load=True)

### 2.2.3 모델 정의

계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층으로 합성곱층(convolutional layer), 선형계층(linear layer)

모듈(module): 한 개 이상의 계층이 모여서 구성된 것.

모델(model): 최종적으로 원하는 네트워크

#### 단순 신경망을 정의하는 방법

In [ ]:
# model=nn.Linear(in_features=1,out_features=1,bias=True)

#### nn.Moduel()을 상속하여 정의하는 방법

In [ ]:
#class MLP(Module):
#  def __init__(self,inputs):
#    super(MLP,self).__init__()
#    self.layer=Linear(inputs,1)
#    self.activation=Sigmoid()

#  def forward(self,X):
#    X=self.layer(X)
#    X=self.activation(X)
#    return X

#### Sequential 신경망을 정의하는 방법

nn.Sequential: 네트워크 모델 정의, 계층이 복잡할수록 효과가 뛰어남.

model.modules(): 모델의 네트워크에 대한 모든 노드 반환

model.children(): 같은 수주의 하위 노드 반환

In [12]:
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
    super(MLP,self).__init__()
    self.layer1=nn.Sequential(
        nn.Conv2d(in_channels=3,out_channels=64,kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer2=nn.Sequential(
        nn.Conv2d(in_channels=64,out_channels=30,kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3=nn.Sequential(
        nn.Linear(in_features=30*5*5,out_features=10,bias=True),
        nn.ReLU(inplace=True))

    def forward(self,x):
      x=self.layer1(x)
      x=self.layer2(x)
      x=x.view(x.shape[0],-1)
      x=self.layer3(x)
      return x
model=MLP() # 모델에 대한 객체 생성

print("Printing children\n------------------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n------------------------------")
print(list(model.modules()))

Printing children
------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linea

#### 함수로 신경망을 정의하는 방법

nn.Model() 상속받아 사용.

In [13]:
def MLP(in_features=1,hidden_features=20,out_features=1):
  hidden=nn.Linear(in_features=in_features,out_features=hidden_features,
                   bias=True)
  activation=nn.ReLU()
  output=nn.Linear(in_features=hidden_features,out_features=out_features,
                   bias=True)
  net=nn.Sequential(hidden,activation,output)
  return net

### 2.2.4 모델의 파라미터 정의

**손실 함수**(loss function): 학습하는 동안 출력과 실제 값 사이의 오차 측정
- BCELoss: 이진 분류
- CrossEntropyLoss: 다중 클래스 분류
- MSELoss: 회귀 모델

**옵티마이저**(optimizer): 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법 결정.

**학습률 스케줄러**(learning rate scheduler): 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시킴.
- optim.lr_scheduler.LambdaLR
- optim.lr_scheduler.StepLR
- optim.lr_scheduler.MultiStepLR
- optim.lr_scheduler.ExponentialLR
- optim.lr_scheduler.CosineAnnealingLR
- optim.lr_scheduler.CosineAnnealingLR

**지표**: 훈련과 테스트 단계 모니터링

In [15]:
# from torch.optim import optimizer
# criterion=torch.nn.MSELoss()
# optimizer=torch.optim.SGD(model.parameters(),lr=0.01,momentum=0.9)
# scheduler=torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,
#                                            lr_lambda=lambda epoch: 0.95**epoch)
# for epoch in range(1,100+!):
#     for x,y in dataloader:
#                   optimizer.zero_grad()
# loss_fn(model(x),y).backward()
# optimizer.step()
# scheduler.step()

### 2.2.5 모델 훈련

모델, 손실 함수, 옵티마이저 정의

-> optimizer.zero_grad(): 전방향 학습, 기울기 초기화

-> output=model(input): 출력 계산

-> loss=loss_fn(output,target): 오차 계산

-> loss.backword(): 역전파 학습

-> optimizer.step(): 기울기 업데이트

In [17]:
# for epoch in range(100):
#   yhat=model(x_train)
#   loss=criterion(yhat,y_train)
#   optimizer.zero_grad()
#   loss.backward()
#   optimizer.step()

### 2.2.6 모델 평가

In [18]:
! pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 58.8 MB/s eta 0:00:00


In [20]:
import torch
import torchmetrics

preds=torch.randn(10,5).softmax(dim=-1)
target=torch.randint(5,(10,))

acc=torchmetrics.functional.accuracy(preds,target,task='multiclass', num_classes=5)
# 모델을 평가하기 위해 torchmetrics, functional.accuracy 이용

In [23]:
import torch
import torchmetrics
metric=torchmetrics.Accuracy(task='multiclass', num_classes=5) # 모델 평가(정확도) 초기화

n_batches=10
for i in range(n_batches):
  preds=torch.randn(10,5).softmax(dim=-1)
  target=torch.randint(5,(10,))

  acc=metric(preds,target)
  print(f"Accuracy on batch {i}: {acc}") # 현재 배치에서 모델 평가(정확도)

acc=metric.compute()
print(f"Accuracy on all data: {acc}") # 모든 배치에서 모델 평가(정확도)

Accuracy on batch 0: 0.30000001192092896
Accuracy on batch 1: 0.10000000149011612
Accuracy on batch 2: 0.10000000149011612
Accuracy on batch 3: 0.30000001192092896
Accuracy on batch 4: 0.10000000149011612
Accuracy on batch 5: 0.30000001192092896
Accuracy on batch 6: 0.10000000149011612
Accuracy on batch 7: 0.30000001192092896
Accuracy on batch 8: 0.4000000059604645
Accuracy on batch 9: 0.0
Accuracy on all data: 0.20000000298023224


### 2.2.7 훈련 과정 모니터링

1. 텐서보드를 설정(set up)
2. 텐서보드에 기록(write)
3. 텐서보드를 사용하여 모델 구조를 살펴봄.

model.train: 훈련 데이터셋에 사용하며 모델 훈련이 진행될 것을 알림. 드롭아웃 활성화.

model.eval: 모델 평가할 때 모든 노드를 사용하겠따는 의미로 검증과 테스트 데이터셋에 사용.

In [24]:
# ! pip install tensorboard

In [25]:
# import torch
# from torch.utils.tensorboard import SummaryWriter
# writer=SummaryWriter("../chap02/tensorboard")

# for epoch in range(num_epochs):
#  model.train()
#  batch_loss=0.0

#  for i,(x,y) in enumerate(dataloader):
#    x,y=x.to(device).float(), y.to(device).float()
#    outputs=model(x)
#    loss=criterion(outputs,y)
#    writer.add_sca1ar("Loss" loss,epoch)
#    optimizer.zero_grad()
#    loss.backward()
#    optimizer.step()

# writer.close()

In [ ]:
# tensorboard --logdir=../chap02/tensorboard --port=6006

In [ ]:
# model.eval()
# with torch.no_grad():
#     valid_loss=0

#     for x,y in valid_dataloader:
#         outputs=model(x)
#         loss=F.cross_entropy(outputs,y.long().squeeze())
#         valid_loss += float(loss)
#         y_hat += [outputs]

# valid_loss=valid_loss/len(valid_loader)