<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/YB_0905_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [2]:
matrix21=np.random.random((5,3))
matrix21_2=np.random.random((3,2))
print(np.dot(matrix21,matrix21_2))

[[1.46585157 0.69036797]
 [1.67137239 0.76138317]
 [1.34810077 0.40280565]
 [1.21321441 0.61858167]
 [0.52834132 0.16169537]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
array22=np.arange(10)
array22[(array22>3) & (array22<8)]=-array22[(array22>3) & (array22<8)]
print(array22)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
# Author: Jake VanderPlas

print(sum(range(5),-1)) # 답: 9
from numpy import *
print(sum(range(5),-1)) # 답: 10

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [6]:
Z=np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# legal

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [8]:
print(Z<Z>Z)
# 오류 발생. > illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [10]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [12]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 4 6 7]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [13]:
np.sqrt(-1) == np.emath.sqrt(-1) # False

/tmp/ipython-input-244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [16]:
Z=np.arange('2016-07-01','2016-08-01',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [17]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [25]:
array30=np.random.uniform(0,10,10)
print(array30)
# 1
intpart=array30//1
print(intpart)
# 2
intpart2=array30-array30%1
print(intpart2)

[5.68314484 7.15845756 9.75544403 7.55859013 5.14030176 4.42217493
 9.69591514 6.74905269 2.10737901 6.87357298]
[5. 7. 9. 7. 5. 4. 9. 6. 2. 6.]
[5. 7. 9. 7. 5. 4. 9. 6. 2. 6.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [26]:
matrix31=np.zeros((5,5))
matrix31+=np.arange(5)
print(matrix31)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [28]:
vector32=np.random.random(10)
print(vector32)
vector32_2=np.sort(vector32)
print(vector32_2)

[0.90999555 0.90530254 0.4381874  0.96034921 0.90362891 0.15659528
 0.4134472  0.23212973 0.05833318 0.09415495]
[0.05833318 0.09415495 0.15659528 0.23212973 0.4134472  0.4381874
 0.90362891 0.90530254 0.90999555 0.96034921]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [29]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B) # False

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [32]:
matrix34=np.random.random((10,2))
X,Y=matrix34[:,0],matrix34[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.74292799 0.74216727 0.35765024 1.04620664 1.09443226 0.91293641
 0.84257008 0.35415769 0.13023069 0.28346077]
[1.54461046 0.23722962 0.78129918 1.21707376 0.45886915 1.36815689
 0.99283066 0.70490702 1.29021992 0.8739552 ]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [21]:
Z=np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.74136887 0.8629729  0.60632003 0.71644834 0.96959934 0.83747801
 0.25165631 0.56181025 0.66126598 0.88443003]
[0.74136887 0.8629729  0.60632003 0.71644834 0.         0.83747801
 0.25165631 0.56181025 0.66126598 0.88443003]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [24]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
print(np.argmin(np.abs(Z-v)))

53.85882414513844
54


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [33]:
array37=np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array37):
  print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [30]:
n=3
p=2
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),8)
print(Z)

[[0. 8. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [34]:
# 1st column
Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[1 8 5]
 [4 5 4]
 [1 6 2]]
[[1 8 5]
 [1 6 2]
 [4 5 4]]


In [35]:
# 2nd column
Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 8 3]
 [0 9 2]
 [2 4 7]]
[[2 4 7]
 [2 8 3]
 [0 9 2]]


In [36]:
# 3rd column
Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[5 5 0]
 [4 2 7]
 [5 7 1]]
[[5 5 0]
 [5 7 1]
 [4 2 7]]
